[package]
name = "laf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
rand = "0.8.5"
uuid = { version = "1.2.1", features = ["v1", "v3", "v4", "v5", "fast-rng"] }
